name: ansi_color_palette
version: 1.2.1-dev
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A custom element to pick ANSI colors
homepage: https://github.com/kui/ansi_color_palette
environment:
  sdk: '>=1.6.0'
dependencies:
  color_palette: '>=1.2.0 <1.3.0'
  polymer: '>=0.13.0 <0.14.0'
dev_dependencies:
  ghpages_generator: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <1.3.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
