name: ansi_color_palette
version: 1.3.0
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A custom element to pick ANSI colors
homepage: https://github.com/kui/ansi_color_palette
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '>=0.16.0 <0.17.0'
  core_elements: '>=0.7.1 <0.8.0'
  color_palette: '>=1.3.0 <1.4.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
